name: ux4g_flutter_design_system
description: "Flutter implementation of the UX4G design system components and foundations."
version: 0.0.1
homepage: https://github.com/ux4g-negd/ux4g-flutter-design-system
repository: https://github.com/ux4g-negd/ux4g-flutter-design-system
issue_tracker: https://github.com/ux4g-negd/ux4g-flutter-design-system/issues

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
